
[[constraint]]
  name = "github.com/asdine/storm"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/decred/dcrd"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"
